import pandas as pd
import numpy as np
df2 = pd.read_csv(r'train.csv')
df2['MSZoning'] = df2['MSZoning'].map({'RL':0, 'RM':1, 'C (all)':2, 'FV':3, 'RH':4})
df2['Street'] = df2['Street'].map({'Pave':0, 'Grvl':1})
df2['Alley'] = df2['Alley'].map({'Grvl':0, 'Pave':1, 'NA':2})
df2['LotShape'] = df2['LotShape'].map({'Reg':0, 'IR1':1, 'IR2':2, 'IR3':3})
df2['LandContour'] = df2['LandContour'].map({'Lvl':0, 'Bnk':1, 'HLS':2, 'Low':3})
df2['Utilities'] = df2['Utilities'].map({'AllPub':0})
df2['LotConfig'] = df2['LotConfig'].map({'Inside':0, 'Corner':1, 'CulDSac':2, 'FR2':3, 'FR3':4})
df2['LandSlope'] = df2['LandSlope'].map({'Gtl':0, 'Mod':1, 'Sev':2})
df2['Neighborhood'] = df2['Neighborhood'].map({'NAmes':0, 'CollgCr':1, 'OldTown':2, 'Edwards':3, 'Somerst':4, 'Gilbert':5, 'NridgHt':6, 'Sawyer':7, 'NWAmes':8, 'SawyerW':9, 'BrkSide':10, 'Crawfor':11, 'Mitchel':12, 'NoRidge':13, 'Timber':14, 'IDOTRR':15, 'ClearCr':16, 'SWISU':17, 'StoneBr':18, 'Blmngtn':19, 'MeadowV':20, 'BrDale':21, 'Veenker':22, 'NPkVill':23, 'Blueste':24})
df2['Condition1'] = df2['Condition1'].map({'Norm':0, 'Feedr':1, 'Artery':2, 'RRAn':3, 'PosN':4, 'RRAe':5, 'PosA':6, 'RRNn':7, 'RRNe':8})
df2['Condition2'] = df2['Condition2'].map({'Norm':0, 'Feedr':1, 'Artery':2, 'RRAn':3, 'PosN':4, 'RRAe':5, 'PosA':6, 'RRNn':7, 'RRNe':8})
df2['BldgType'] = df2['BldgType'].map({'1Fam':0, 'TwnhsE':1, 'Duplex':2, 'Twnhs':3, '2fmCon':4})
df2['HouseStyle'] = df2['HouseStyle'].map({'1Story':0, '2Story':1, '1.5Fin':2, 'SLvl':3, 'SFoyer':4, '1.5Unf':5, '2.5Unf':6, '2.5Fin':7})
df2['RoofStyle'] = df2['RoofStyle'].map({'Gable':0, 'Hip':1, 'Flat':2, 'Gambrel':3, 'Mansard':4, 'Shed':5})
df2['RoofMatl'] = df2['RoofMatl'].map({'CompShg':0, 'Tar&Grv':1, 'WdShngl':2, 'WdShake':3, 'Metal':4, 'Membran':5, 'Roll':6, 'ClyTile':7})
df2['Exterior1st'] = df2['Exterior1st'].map({'VinylSd':0, 'HdBoard':1, 'MetalSd':2, 'Wd Sdng':3, 'Plywood':4, 'CemntBd':5, 'BrkFace':6, 'WdShing':7, 'Stucco':8, 'AsbShng':9, 'Stone':10, 'BrkComm':11, 'AsphShn':12, 'CBlock':13, 'ImStucc':14})
df2['Exterior2nd'] = df2['Exterior2nd'].map({'VinylSd':0, 'HdBoard':1, 'MetalSd':2, 'Wd Sdng':3, 'Plywood':4, 'CmentBd':5, 'Wd Shng':6, 'Stucco':7, 'BrkFace':8, 'AsbShng':9, 'ImStucc':10, 'Brk Cmn':11, 'Stone':12, 'AsphShn':13, 'CBlock':14, 'Other':15})
df2['MasVnrType'] = df2['MasVnrType'].map({'BrkFace':0, 'None':1, 'Stone':2, 'BrkCmn':3})
df2['ExterQual'] = df2['ExterQual'].map({'TA':0, 'Gd':1, 'Ex':2, 'Fa':3})
df2['ExterCond'] = df2['ExterCond'].map({'TA':0, 'Gd':1, 'Fa':2, 'Po':3, 'Ex':4})
df2['Foundation'] = df2['Foundation'].map({'PConc':0, 'CBlock':1, 'BrkTil':2, 'Slab':3, 'Stone':4, 'Wood':5})
df2['BsmtQual'] = df2['BsmtQual'].map({'TA':0, 'Gd':1, 'Ex':2, 'Fa':3, 'NA':4})
df2['BsmtCond'] = df2['BsmtCond'].map({'TA':0, 'Gd':1, 'Fa':2, 'Po':3, 'NA':4})
df2['BsmtExposure'] = df2['BsmtExposure'].map({'No':0, 'Av':1, 'Gd':2, 'Mn':3, 'NA':4})
df2['BsmtFinType1'] = df2['BsmtFinType1'].map({'Unf':0, 'GLQ':1, 'ALQ':2, 'BLQ':3, 'Rec':4, 'LwQ':5, 'NA':6})
df2['BsmtFinType2'] = df2['BsmtFinType2'].map({'Unf':0, 'Rec':1, 'LwQ':2, 'BLQ':3, 'ALQ':4, 'GLQ':5, 'NA':6})
df2['Heating'] = df2['Heating'].map({'GasA':0, 'GasW':1, 'Grav':2, 'Wall':3, 'OthW':4, 'Floor':5})
df2['HeatingQC'] = df2['HeatingQC'].map({'Ex':0, 'TA':1, 'Gd':2, 'Fa':3, 'Po':4})
df2['CentralAir'] = df2['CentralAir'].map({'Y':0, 'N':1})
df2['Electrical'] = df2['Electrical'].map({'SBrkr':0, 'FuseA':1, 'FuseF':2, 'FuseP':3, 'Mix':4})
df2['KitchenQual'] = df2['KitchenQual'].map({'TA':0, 'Gd':1, 'Ex':2, 'Fa':3, 'Po':4})
df2['FireplaceQu'] = df2['FireplaceQu'].map({'TA':0, 'Gd':1, 'Fa':2, 'Ex':3, 'Po':4, 'NA':5})
df2['GarageType'] = df2['GarageType'].map({'Attchd':0, 'Detchd':1, 'BuiltIn':2, 'Basment':3, 'CarPort':4, '2Types':5})
df2['GarageFinish'] = df2['GarageFinish'].map({'RFn':0, 'Unf':1, 'Fin':2, 'NA':3})
df2['GarageQual'] = df2['GarageQual'].map({'TA':0, 'Fa':1, 'Gd':2, 'NA':3, 'Ex':4, 'Po':5})
df2['GarageCond'] = df2['GarageCond'].map({'TA':0, 'Fa':1, 'NA':2, 'Gd':3, 'Po':4, 'Ex':5})
df2['PavedDrive'] = df2['PavedDrive'].map({'Y':0, 'N':1, 'P':2})
df2['PoolQC'] = df2['PoolQC'].map({'Gd':0, 'Ex':2, 'Fa':3})
df2['Fence'] = df2['Fence'].map({'MnPrv':0, 'GdWo':1, 'GdPrv':2, 'MnWw':3, 'NA':4})
df2['MiscFeature'] = df2['MiscFeature'].map({'Shed':0, 'Gar2':1, 'Othr':2, 'TenC':3, 'NA':4})
df2['SaleType'] = df2['SaleType'].map({'WD':0, 'New':1, 'COD':2, 'ConLD':3, 'ConLI':4, 'CWD':5, 'ConLw':6, 'Con':7, 'Oth':8})
df2['SaleCondition'] = df2['SaleCondition'].map({'Normal':0, 'Partial':1, 'Abnorml':2, 'Family':3, 'Alloca':4, 'AdjLand':5})
df2['Functional'] = df2['Functional'].map({'Typ':0, 'Min1':1, 'Maj1':2, 'Min2':3, 'Mod':4, 'Maj2':5, 'Sev':6})
df2 = df2.drop(['PoolQC'], axis=1)
df2 = df2.drop(['Fence'], axis=1)
df2 = df2.drop(['MasVnrType'], axis=1)
df2 = df2.drop(['Alley'], axis=1)
df2 = df2.drop(['MiscFeature'], axis=1)
df2 = df2.drop(['LotFrontage'], axis=1)
df2 = df2.drop(['FireplaceQu'], axis=1)
skewed_features = ['GrLivArea', 'LotArea', 'TotalBsmtSF', '1stFlrSF']
for feature in skewed_features:
    df2[feature] = np.log1p(df2[feature])
df2['TotalBath'] = df2['BsmtFullBath'] + (df2['BsmtHalfBath'] * 0.5) + df2['FullBath'] + (df2['HalfBath'] * 0.5)
df2['TotalFloors'] = df2['1stFlrSF']
df2['TotalArea'] = df2['TotalBsmtSF'] + df2['GrLivArea'] + df2['GarageArea']
pd.options.display.max_rows = None
df2 = df2.fillna(method='ffill')
print(df2.isnull().sum())
print(df2.shape)
df2['SalePrice'] = np.log1p(df2['SalePrice'])

df2.to_csv(r'train2.csv', index=False)
print("전처리 완료: train2.csv")



import pandas as pd
import numpy as np
df2 = pd.read_csv(r'test.csv')
df2['MSZoning'] = df2['MSZoning'].map({'RL':0, 'RM':1, 'C (all)':2, 'FV':3, 'RH':4})
df2['Street'] = df2['Street'].map({'Pave':0, 'Grvl':1})
df2['Alley'] = df2['Alley'].map({'Grvl':0, 'Pave':1, 'NA':2})
df2['LotShape'] = df2['LotShape'].map({'Reg':0, 'IR1':1, 'IR2':2, 'IR3':3})
df2['LandContour'] = df2['LandContour'].map({'Lvl':0, 'Bnk':1, 'HLS':2, 'Low':3})
df2['Utilities'] = df2['Utilities'].map({'AllPub':0})
df2['LotConfig'] = df2['LotConfig'].map({'Inside':0, 'Corner':1, 'CulDSac':2, 'FR2':3, 'FR3':4})
df2['LandSlope'] = df2['LandSlope'].map({'Gtl':0, 'Mod':1, 'Sev':2})
df2['Neighborhood'] = df2['Neighborhood'].map({'NAmes':0, 'CollgCr':1, 'OldTown':2, 'Edwards':3, 'Somerst':4, 'Gilbert':5, 'NridgHt':6, 'Sawyer':7, 'NWAmes':8, 'SawyerW':9, 'BrkSide':10, 'Crawfor':11, 'Mitchel':12, 'NoRidge':13, 'Timber':14, 'IDOTRR':15, 'ClearCr':16, 'SWISU':17, 'StoneBr':18, 'Blmngtn':19, 'MeadowV':20, 'BrDale':21, 'Veenker':22, 'NPkVill':23, 'Blueste':24})
df2['Condition1'] = df2['Condition1'].map({'Norm':0, 'Feedr':1, 'Artery':2, 'RRAn':3, 'PosN':4, 'RRAe':5, 'PosA':6, 'RRNn':7, 'RRNe':8})
df2['Condition2'] = df2['Condition2'].map({'Norm':0, 'Feedr':1, 'Artery':2, 'RRAn':3, 'PosN':4, 'RRAe':5, 'PosA':6, 'RRNn':7, 'RRNe':8})
df2['BldgType'] = df2['BldgType'].map({'1Fam':0, 'TwnhsE':1, 'Duplex':2, 'Twnhs':3, '2fmCon':4})
df2['HouseStyle'] = df2['HouseStyle'].map({'1Story':0, '2Story':1, '1.5Fin':2, 'SLvl':3, 'SFoyer':4, '1.5Unf':5, '2.5Unf':6, '2.5Fin':7})
df2['RoofStyle'] = df2['RoofStyle'].map({'Gable':0, 'Hip':1, 'Flat':2, 'Gambrel':3, 'Mansard':4, 'Shed':5})
df2['RoofMatl'] = df2['RoofMatl'].map({'CompShg':0, 'Tar&Grv':1, 'WdShngl':2, 'WdShake':3, 'Metal':4, 'Membran':5, 'Roll':6, 'ClyTile':7})
df2['Exterior1st'] = df2['Exterior1st'].map({'VinylSd':0, 'HdBoard':1, 'MetalSd':2, 'Wd Sdng':3, 'Plywood':4, 'CemntBd':5, 'BrkFace':6, 'WdShing':7, 'Stucco':8, 'AsbShng':9, 'Stone':10, 'BrkComm':11, 'AsphShn':12, 'CBlock':13, 'ImStucc':14})
df2['Exterior2nd'] = df2['Exterior2nd'].map({'VinylSd':0, 'HdBoard':1, 'MetalSd':2, 'Wd Sdng':3, 'Plywood':4, 'CmentBd':5, 'Wd Shng':6, 'Stucco':7, 'BrkFace':8, 'AsbShng':9, 'ImStucc':10, 'Brk Cmn':11, 'Stone':12, 'AsphShn':13, 'CBlock':14, 'Other':15})
df2['MasVnrType'] = df2['MasVnrType'].map({'BrkFace':0, 'None':1, 'Stone':2, 'BrkCmn':3})
df2['ExterQual'] = df2['ExterQual'].map({'TA':0, 'Gd':1, 'Ex':2, 'Fa':3})
df2['ExterCond'] = df2['ExterCond'].map({'TA':0, 'Gd':1, 'Fa':2, 'Po':3, 'Ex':4})
df2['Foundation'] = df2['Foundation'].map({'PConc':0, 'CBlock':1, 'BrkTil':2, 'Slab':3, 'Stone':4, 'Wood':5})
df2['BsmtQual'] = df2['BsmtQual'].map({'TA':0, 'Gd':1, 'Ex':2, 'Fa':3, 'NA':4})
df2['BsmtCond'] = df2['BsmtCond'].map({'TA':0, 'Gd':1, 'Fa':2, 'Po':3, 'NA':4})
df2['BsmtExposure'] = df2['BsmtExposure'].map({'No':0, 'Av':1, 'Gd':2, 'Mn':3, 'NA':4})
df2['BsmtFinType1'] = df2['BsmtFinType1'].map({'Unf':0, 'GLQ':1, 'ALQ':2, 'BLQ':3, 'Rec':4, 'LwQ':5, 'NA':6})
df2['BsmtFinType2'] = df2['BsmtFinType2'].map({'Unf':0, 'Rec':1, 'LwQ':2, 'BLQ':3, 'ALQ':4, 'GLQ':5, 'NA':6})
df2['Heating'] = df2['Heating'].map({'GasA':0, 'GasW':1, 'Grav':2, 'Wall':3, 'OthW':4, 'Floor':5})
df2['HeatingQC'] = df2['HeatingQC'].map({'Ex':0, 'TA':1, 'Gd':2, 'Fa':3, 'Po':4})
df2['CentralAir'] = df2['CentralAir'].map({'Y':0, 'N':1})
df2['Electrical'] = df2['Electrical'].map({'SBrkr':0, 'FuseA':1, 'FuseF':2, 'FuseP':3, 'Mix':4})
df2['KitchenQual'] = df2['KitchenQual'].map({'TA':0, 'Gd':1, 'Ex':2, 'Fa':3, 'Po':4})
df2['FireplaceQu'] = df2['FireplaceQu'].map({'TA':0, 'Gd':1, 'Fa':2, 'Ex':3, 'Po':4, 'NA':5})
df2['GarageType'] = df2['GarageType'].map({'Attchd':0, 'Detchd':1, 'BuiltIn':2, 'Basment':3, 'CarPort':4, '2Types':5})
df2['GarageFinish'] = df2['GarageFinish'].map({'RFn':0, 'Unf':1, 'Fin':2, 'NA':3})
df2['GarageQual'] = df2['GarageQual'].map({'TA':0, 'Fa':1, 'Gd':2, 'NA':3, 'Ex':4, 'Po':5})
df2['GarageCond'] = df2['GarageCond'].map({'TA':0, 'Fa':1, 'NA':2, 'Gd':3, 'Po':4, 'Ex':5})
df2['PavedDrive'] = df2['PavedDrive'].map({'Y':0, 'N':1, 'P':2})
df2['PoolQC'] = df2['PoolQC'].map({'Gd':0, 'Ex':2, 'Fa':3})
df2['Fence'] = df2['Fence'].map({'MnPrv':0, 'GdWo':1, 'GdPrv':2, 'MnWw':3, 'NA':4})
df2['MiscFeature'] = df2['MiscFeature'].map({'Shed':0, 'Gar2':1, 'Othr':2, 'TenC':3, 'NA':4})
df2['SaleType'] = df2['SaleType'].map({'WD':0, 'New':1, 'COD':2, 'ConLD':3, 'ConLI':4, 'CWD':5, 'ConLw':6, 'Con':7, 'Oth':8})
df2['SaleCondition'] = df2['SaleCondition'].map({'Normal':0, 'Partial':1, 'Abnorml':2, 'Family':3, 'Alloca':4, 'AdjLand':5})
df2['Functional'] = df2['Functional'].map({'Typ':0, 'Min1':1, 'Maj1':2, 'Min2':3, 'Mod':4, 'Maj2':5, 'Sev':6})
df2 = df2.drop(['PoolQC'], axis=1)
df2 = df2.drop(['Fence'], axis=1)
df2 = df2.drop(['MasVnrType'], axis=1)
df2 = df2.drop(['Alley'], axis=1)
df2 = df2.drop(['MiscFeature'], axis=1)
df2 = df2.drop(['LotFrontage'], axis=1)
df2 = df2.drop(['FireplaceQu'], axis=1)
skewed_features = ['GrLivArea', 'LotArea', 'TotalBsmtSF', '1stFlrSF']
for feature in skewed_features:
    df2[feature] = np.log1p(df2[feature])
df2['TotalBath'] = df2['BsmtFullBath'] + (df2['BsmtHalfBath'] * 0.5) + df2['FullBath'] + (df2['HalfBath'] * 0.5)
df2['TotalFloors'] = df2['1stFlrSF']
df2['TotalArea'] = df2['TotalBsmtSF'] + df2['GrLivArea'] + df2['GarageArea']
pd.options.display.max_rows = None
df2 = df2.fillna(method='ffill')
print(df2.isnull().sum())
print(df2.shape)

df2.to_csv(r'test2.csv', index=False)
print("전처리 완료: test2.csv")
